_SPS_Length("World length of mesh (m)", Float) = 0
_SPS_BakedLength("World length of mesh when baked (m)", Float) = 0
_SPS_Bake("Baked mesh info", 2D) = "white" {}
_SPS_Enabled("Enabled (0-1)", Float) = 1
_SPS_Overrun("Overrun", Float) = 1
_SPS_BlendshapeVertCount("Baked blendshape vert count", Float) = 0
_SPS_BlendshapeCount("Blendshape Count", Float) = 0
_SPS_Blendshape0("Blendshape 0", Float) = 0
_SPS_Blendshape1("Blendshape 1", Float) = 0
_SPS_Blendshape2("Blendshape 2", Float) = 0
_SPS_Blendshape3("Blendshape 3", Float) = 0
_SPS_Blendshape4("Blendshape 4", Float) = 0
_SPS_Blendshape5("Blendshape 5", Float) = 0
_SPS_Blendshape6("Blendshape 6", Float) = 0
_SPS_Blendshape7("Blendshape 7", Float) = 0
_SPS_Blendshape8("Blendshape 8", Float) = 0
_SPS_Blendshape9("Blendshape 9", Float) = 0
_SPS_Blendshape10("Blendshape 10", Float) = 0
_SPS_Blendshape11("Blendshape 11", Float) = 0
_SPS_Blendshape12("Blendshape 12", Float) = 0
_SPS_Blendshape13("Blendshape 13", Float) = 0
_SPS_Blendshape14("Blendshape 14", Float) = 0
_SPS_Blendshape15("Blendshape 15", Float) = 0
_SPS_Tri_Enabled("Triangulation Enabled", Float) = 0
_SPS_Tri_Root_Center("Triangulation Root Center", Float) = 0
_SPS_Tri_Root_Forward("Triangulation Root Forward", Float) = 0
_SPS_Tri_Root_Up("Triangulation Root Up", Float) = 0
_SPS_Tri_Root_Right("Triangulation Root Right", Float) = 0
_SPS_Tri_Front_Center("Triangulation Front Center", Float) = 0
_SPS_Tri_Front_Forward("Triangulation Front Forward", Float) = 0
_SPS_Tri_Front_Up("Triangulation Front Up", Float) = 0
_SPS_Tri_Front_Right("Triangulation Front Right", Float) = 0
_SPS_Tri_IsRing("Triangulation IsRing", Float) = 0
_SPS_Tri_IsHole("Triangulation IsHole", Float) = 0
