[Header(SPS)]
_SPS_Length("World length of mesh (m)", Float) = 0
_SPS_BakedLength("World length of mesh when baked (m)", Float) = 0
_SPS_Bake("Baked mesh info", 2D) = "white" {}
_SPS_Enabled("Enabled (0-1)", Float) = 1
_SPS_Overrun("Overrun", Float) = 1
_SPS_BlendshapeVertCount("Baked blendshape vert count", Float) = 0
_SPS_BlendshapeCount("Blendshape Count", Float) = 0
_SPS_Blendshape0("Blendshape 0", Float) = 0
_SPS_Blendshape1("Blendshape 1", Float) = 0
_SPS_Blendshape2("Blendshape 2", Float) = 0
_SPS_Blendshape3("Blendshape 3", Float) = 0
_SPS_Blendshape4("Blendshape 4", Float) = 0
_SPS_Blendshape5("Blendshape 5", Float) = 0
_SPS_Blendshape6("Blendshape 6", Float) = 0
_SPS_Blendshape7("Blendshape 7", Float) = 0
_SPS_Blendshape8("Blendshape 8", Float) = 0
_SPS_Blendshape9("Blendshape 9", Float) = 0
_SPS_Blendshape10("Blendshape 10", Float) = 0
_SPS_Blendshape11("Blendshape 11", Float) = 0
_SPS_Blendshape12("Blendshape 12", Float) = 0
_SPS_Blendshape13("Blendshape 13", Float) = 0
_SPS_Blendshape14("Blendshape 14", Float) = 0
_SPS_Blendshape15("Blendshape 15", Float) = 0

_SPS_Target_LL_Lights("Target SPSLL Lights", Float) = 1

_SPS_Tri_Self_Enabled("_SPS_Tri_Self_Enabled", Float) = 0
_SPS_Tri_Self_Root_Center("_SPS_Tri_Self_Root_Center", Float) = 0
_SPS_Tri_Self_Root_Forward("_SPS_Tri_Self_Root_Forward", Float) = 0
_SPS_Tri_Self_Root_Up("_SPS_Tri_Self_Root_Up", Float) = 0
_SPS_Tri_Self_Root_Right("_SPS_Tri_Self_Root_Right", Float) = 0
_SPS_Tri_Self_Front_Center("_SPS_Tri_Self_Front_Center", Float) = 0
_SPS_Tri_Self_Front_Forward("_SPS_Tri_Self_Front_Forward", Float) = 0
_SPS_Tri_Self_Front_Up("_SPS_Tri_Self_Front_Up", Float) = 0
_SPS_Tri_Self_Front_Right("_SPS_Tri_Self_Front_Right", Float) = 0
_SPS_Tri_Self_IsRing("_SPS_Tri_Self_IsRing", Float) = 0
_SPS_Tri_Self_IsHole("_SPS_Tri_Self_IsHole", Float) = 0

_SPS_Tri_Other_Enabled("_SPS_Tri_Other_Enabled", Float) = 0
_SPS_Tri_Other_Root_Center("_SPS_Tri_Other_Root_Center", Float) = 0
_SPS_Tri_Other_Root_Forward("_SPS_Tri_Other_Root_Forward", Float) = 0
_SPS_Tri_Other_Root_Up("_SPS_Tri_Other_Root_Up", Float) = 0
_SPS_Tri_Other_Root_Right("_SPS_Tri_Other_Root_Right", Float) = 0
_SPS_Tri_Other_Front_Center("_SPS_Tri_Other_Front_Center", Float) = 0
_SPS_Tri_Other_Front_Forward("_SPS_Tri_Other_Front_Forward", Float) = 0
_SPS_Tri_Other_Front_Up("_SPS_Tri_Other_Front_Up", Float) = 0
_SPS_Tri_Other_Front_Right("_SPS_Tri_Other_Front_Right", Float) = 0
_SPS_Tri_Other_IsRing("_SPS_Tri_Other_IsRing", Float) = 0
_SPS_Tri_Other_IsHole("_SPS_Tri_Other_IsHole", Float) = 0
