blank_issues_enabled: false
contact_links:
  - name: VRCFury User? Click here.
    url: https://vrcfury.com/discord
    about: All bug reports, feature requests, and support should be posted to our Discord server. Unique, valid concerns will be converted to a Github issue for you.
